export * from './capitalize.pipe';
export * from './plural.pipe';
export * from './round.pipe';
export * from './timing.pipe';
export * from './number-with-commas.pipe';
export * from './cpf.pipe';
export * from './date.pipe';
export * from './telefone.pipe';
export * from './cep.pipe';
